import type { Category, Product } from "./types";
import { photosFor } from "./photos";

export const categories: Category[] = [
  { slug: "audio", name: "Audio", tagline: "Hear everything", hues: ["#7c5cff", "#2b1b6b"], shape: "headphones" },
  { slug: "wearables", name: "Wearables", tagline: "Wrist-first tech", hues: ["#ff4d8d", "#5b1135"], shape: "watch" },
  { slug: "computing", name: "Computing", tagline: "Power on demand", hues: ["#3dd6ff", "#0b3b52"], shape: "laptop" },
  { slug: "phones", name: "Phones", tagline: "Pocket flagships", hues: ["#c6ff3d", "#2f4a05"], shape: "phone" },
  { slug: "cameras", name: "Cameras", tagline: "Capture the moment", hues: ["#ffb13d", "#5a3405"], shape: "camera" },
  { slug: "footwear", name: "Footwear", tagline: "Step up", hues: ["#ff6b3d", "#5c1c08"], shape: "sneaker" },
  { slug: "fashion", name: "Fashion", tagline: "Built for weather", hues: ["#9aa4b8", "#232a38"], shape: "hoodie" },
  { slug: "home", name: "Home", tagline: "Make it yours", hues: ["#ffd86b", "#4d3a0a"], shape: "lamp" },
];

const COLORS = {
  graphite: { name: "Graphite", hex: "#2a2d36" },
  ivory: { name: "Ivory", hex: "#ece6d8" },
  violet: { name: "Violet", hex: "#7c5cff" },
  lime: { name: "Lime", hex: "#c6ff3d" },
  coral: { name: "Coral", hex: "#ff6b5e" },
  sky: { name: "Sky", hex: "#4cc3ff" },
  forest: { name: "Forest", hex: "#2f6b4f" },
  sand: { name: "Sand", hex: "#cdb48b" },
  midnight: { name: "Midnight", hex: "#141a33" },
  rose: { name: "Rose", hex: "#ff7aa8" },
  silver: { name: "Silver", hex: "#c9ced8" },
  amber: { name: "Amber", hex: "#ffb13d" },
};

const SHOE_SIZES = ["7", "8", "9", "10", "11", "12", "13"];
const APPAREL_SIZES = ["XS", "S", "M", "L", "XL", "XXL"];

const DAY = 86_400_000;
const NOW = 1_760_000_000_000;

const catalog: Product[] = [
  {
    id: "p01",
    slug: "auralux-studio-pro-anc-headphones",
    name: "Studio Pro ANC Headphones",
    brand: "Auralux",
    category: "audio",
    shape: "headphones",
    price: 349,
    compareAt: 429,
    rating: 4.8,
    reviewCount: 2184,
    stock: 42,
    badge: "Best seller",
    hues: ["#7c5cff", "#1d1247"],
    colors: [COLORS.graphite, COLORS.ivory, COLORS.violet],
    tagline: "Adaptive noise cancelling that learns your world.",
    description:
      "Studio Pro pairs 40mm beryllium drivers with eight-mic adaptive noise cancelling for a soundstage that feels like the room disappeared. Forty hours of battery, multipoint Bluetooth and a foldable travel case mean it goes everywhere you do.",
    highlights: ["Adaptive ANC with transparency mode", "40-hour battery, 5-min quick charge for 5 hours", "Multipoint Bluetooth 5.4 + lossless USB-C", "Memory-foam ear cushions"],
    specs: { Driver: "40mm beryllium", Battery: "40 hours", Weight: "254 g", Connectivity: "Bluetooth 5.4, USB-C, 3.5mm", Warranty: "2 years" },
    addedAt: NOW - 30 * DAY,
  },
  {
    id: "p02",
    slug: "auralux-buds-air",
    name: "Buds Air True Wireless",
    brand: "Auralux",
    category: "audio",
    shape: "buds",
    price: 129,
    compareAt: 159,
    rating: 4.6,
    reviewCount: 5120,
    stock: 120,
    hues: ["#a78bfa", "#2a1a63"],
    colors: [COLORS.ivory, COLORS.graphite, COLORS.rose],
    tagline: "Tiny buds. Enormous bass.",
    description:
      "A featherweight fit with a 10mm dynamic driver and hybrid ANC. Wireless charging case included, IPX5 sweat resistance, and six microphones that keep your calls crystal clear.",
    highlights: ["Hybrid ANC", "8h buds + 24h case", "IPX5 water resistance", "Wireless charging case"],
    specs: { Driver: "10mm dynamic", Battery: "8h (+24h case)", Weight: "5 g per bud", Rating: "IPX5", Warranty: "1 year" },
    addedAt: NOW - 60 * DAY,
  },
  {
    id: "p03",
    slug: "boomline-portable-speaker",
    name: "Boom 360 Portable Speaker",
    brand: "Boomline",
    category: "audio",
    shape: "speaker",
    price: 149,
    compareAt: 199,
    rating: 4.7,
    reviewCount: 1873,
    stock: 64,
    badge: "Limited",
    hues: ["#6d5dfc", "#150f3a"],
    colors: [COLORS.coral, COLORS.graphite, COLORS.sky],
    tagline: "Room-filling 360° sound, anywhere.",
    description:
      "Waterproof, dustproof and unreasonably loud. Boom 360 delivers 24 hours of playtime and links with other Boom speakers for party-wide stereo.",
    highlights: ["360° sound", "24h playtime", "IP67 waterproof", "PartyLink for 100+ speakers"],
    specs: { Output: "60W RMS", Battery: "24 hours", Weight: "1.1 kg", Rating: "IP67", Warranty: "1 year" },
    addedAt: NOW - 90 * DAY,
  },
  {
    id: "p04",
    slug: "pulse-watch-ultra",
    name: "Watch Ultra Titanium",
    brand: "Pulse",
    category: "wearables",
    shape: "watch",
    price: 499,
    rating: 4.9,
    reviewCount: 3340,
    stock: 28,
    badge: "New",
    hues: ["#ff4d8d", "#3b0a20"],
    colors: [COLORS.graphite, COLORS.silver, COLORS.amber],
    tagline: "Built for the summit and the stand-up.",
    description:
      "Grade-5 titanium, a sapphire display that hits 3000 nits, dual-frequency GPS and a 72-hour battery. Dive, climb, run - and still make it to brunch.",
    highlights: ["Titanium case, sapphire glass", "72-hour battery", "Dual-frequency GPS", "ECG, SpO2 and temperature sensing"],
    specs: { Display: "1.9\" LTPO AMOLED", Battery: "72 hours", "Water resistance": "100 m", Weight: "61 g", Warranty: "2 years" },
    addedAt: NOW - 6 * DAY,
  },
  {
    id: "p05",
    slug: "pulse-band-3",
    name: "Band 3 Fitness Tracker",
    brand: "Pulse",
    category: "wearables",
    shape: "watch",
    price: 79,
    compareAt: 109,
    rating: 4.4,
    reviewCount: 8021,
    stock: 300,
    hues: ["#ff7aa8", "#4d1230"],
    colors: [COLORS.graphite, COLORS.lime, COLORS.rose],
    tagline: "Everyday health, two-week battery.",
    description:
      "Heart rate, sleep stages, 100+ workout modes and a bright AMOLED display in a band so light you'll forget it's there.",
    highlights: ["14-day battery", "100+ workout modes", "Sleep + stress tracking", "5 ATM water resistance"],
    specs: { Display: "1.47\" AMOLED", Battery: "14 days", Weight: "22 g", "Water resistance": "5 ATM", Warranty: "1 year" },
    addedAt: NOW - 120 * DAY,
  },
  {
    id: "p06",
    slug: "orbitek-zenith-16-laptop",
    name: "Zenith 16 Creator Laptop",
    brand: "Orbitek",
    category: "computing",
    shape: "laptop",
    price: 1799,
    compareAt: 1999,
    rating: 4.8,
    reviewCount: 942,
    stock: 15,
    badge: "Editor's pick",
    hues: ["#3dd6ff", "#06263a"],
    colors: [COLORS.silver, COLORS.graphite],
    tagline: "Desktop-class power. Backpack-class weight.",
    description:
      "A 16-inch mini-LED display, 14-core processor and 32GB of unified memory make Zenith 16 a portable studio. Render 8K timelines, compile giant projects, then unplug for 18 hours.",
    highlights: ["16\" mini-LED, 1600 nits, 120Hz", "14-core CPU / 32GB RAM / 1TB SSD", "18-hour battery", "Thunderbolt 5 x3"],
    specs: { Display: "16\" 3456x2160", Memory: "32GB", Storage: "1TB NVMe", Weight: "1.9 kg", Warranty: "2 years" },
    addedAt: NOW - 20 * DAY,
  },
  {
    id: "p07",
    slug: "orbitek-air-13",
    name: "Air 13 Ultraportable",
    brand: "Orbitek",
    category: "computing",
    shape: "laptop",
    price: 1099,
    compareAt: 1249,
    rating: 4.7,
    reviewCount: 2210,
    stock: 55,
    hues: ["#4cc3ff", "#0a2540"],
    colors: [COLORS.silver, COLORS.midnight, COLORS.sand],
    tagline: "Thin, silent, endlessly capable.",
    description:
      "Fanless, 1.1kg and 11mm thin with a stunning 2.8K display. Air 13 is the laptop for coffee shops, classrooms and everything in between.",
    highlights: ["Fanless silent design", "2.8K OLED display", "20-hour battery", "1.1 kg"],
    specs: { Display: "13.3\" 2.8K OLED", Memory: "16GB", Storage: "512GB", Weight: "1.1 kg", Warranty: "1 year" },
    addedAt: NOW - 45 * DAY,
  },
  {
    id: "p08",
    slug: "keystone-mechanical-keyboard",
    name: "Keystone 75 Mechanical Keyboard",
    brand: "Keystone",
    category: "computing",
    shape: "keyboard",
    price: 159,
    rating: 4.7,
    reviewCount: 1530,
    stock: 80,
    hues: ["#22d3ee", "#0b2f3a"],
    colors: [COLORS.graphite, COLORS.ivory, COLORS.lime],
    tagline: "The thock you've been looking for.",
    description:
      "Gasket-mounted, hot-swappable and tuned out of the box. Keystone 75 connects over Bluetooth, 2.4GHz or USB-C with per-key RGB and a CNC aluminum case.",
    highlights: ["Hot-swappable switches", "Gasket mount, PE foam", "Tri-mode wireless", "Per-key RGB"],
    specs: { Layout: "75% (84 keys)", Case: "CNC aluminum", Battery: "4000 mAh", Weight: "1.2 kg", Warranty: "1 year" },
    addedAt: NOW - 75 * DAY,
  },
  {
    id: "p09",
    slug: "pixelon-vision-5g",
    name: "Vision 5G Smartphone",
    brand: "Pixelon",
    category: "phones",
    shape: "phone",
    price: 899,
    rating: 4.7,
    reviewCount: 4410,
    stock: 70,
    badge: "Best seller",
    hues: ["#c6ff3d", "#233a02"],
    colors: [COLORS.graphite, COLORS.lime, COLORS.sky],
    tagline: "A camera system that sees in the dark.",
    description:
      "A 6.7-inch 120Hz OLED, triple 50MP camera system and all-day battery with 80W wired charging. Seven years of software updates are included.",
    highlights: ["50MP triple camera", "6.7\" 120Hz OLED", "80W charging (0-100% in 35 min)", "7 years of updates"],
    specs: { Display: "6.7\" OLED 120Hz", Storage: "256GB", Battery: "5000 mAh", Weight: "198 g", Warranty: "2 years" },
    addedAt: NOW - 40 * DAY,
  },
  {
    id: "p10",
    slug: "pixelon-lite",
    name: "Lite Smartphone",
    brand: "Pixelon",
    category: "phones",
    shape: "phone",
    price: 399,
    compareAt: 479,
    rating: 4.5,
    reviewCount: 6102,
    stock: 190,
    hues: ["#a3e635", "#1e3305"],
    colors: [COLORS.ivory, COLORS.graphite, COLORS.coral],
    tagline: "Flagship feel, friendly price.",
    description:
      "Smooth 90Hz display, dual-camera system and a two-day battery. Lite proves you don't need to spend big to feel good about your phone.",
    highlights: ["6.4\" 90Hz AMOLED", "Two-day battery", "Dual 48MP camera", "5G ready"],
    specs: { Display: "6.4\" AMOLED 90Hz", Storage: "128GB", Battery: "5200 mAh", Weight: "181 g", Warranty: "1 year" },
    addedAt: NOW - 150 * DAY,
  },
  {
    id: "p11",
    slug: "pixelon-fold-x",
    name: "Fold X Foldable",
    brand: "Pixelon",
    category: "phones",
    shape: "phone",
    price: 1599,
    rating: 4.6,
    reviewCount: 612,
    stock: 9,
    badge: "Limited",
    hues: ["#d9f99d", "#2c3d0b"],
    colors: [COLORS.midnight, COLORS.silver],
    tagline: "Two screens. Zero compromises.",
    description:
      "An 8-inch folding display that opens into a tablet, with a crease-free hinge rated for 400,000 folds. Multitask like never before.",
    highlights: ["8\" foldable 120Hz LTPO", "Crease-minimizing hinge", "Desktop mode", "IPX8 water resistance"],
    specs: { "Inner display": "8.0\" LTPO", Storage: "512GB", Battery: "4800 mAh", Weight: "239 g", Warranty: "2 years" },
    addedAt: NOW - 12 * DAY,
  },
  {
    id: "p12",
    slug: "lumen-x100-mirrorless-camera",
    name: "X100 Mirrorless Camera",
    brand: "Lumen",
    category: "cameras",
    shape: "camera",
    price: 1299,
    compareAt: 1499,
    rating: 4.9,
    reviewCount: 760,
    stock: 21,
    badge: "Editor's pick",
    hues: ["#ffb13d", "#3d2402"],
    colors: [COLORS.graphite, COLORS.silver],
    tagline: "Full-frame fidelity in a pocketable body.",
    description:
      "33MP full-frame stacked sensor, 8-stop in-body stabilization and 6K/60 video. Includes a 28-70mm kit lens built for hybrid shooters.",
    highlights: ["33MP full-frame sensor", "8-stop IBIS", "6K/60p video", "Dual card slots"],
    specs: { Sensor: "33MP full-frame", Video: "6K 60p / 4K 120p", Weight: "658 g", Mount: "L-mount", Warranty: "2 years" },
    addedAt: NOW - 25 * DAY,
  },
  {
    id: "p13",
    slug: "lumen-instant-mini",
    name: "Instant Mini Camera",
    brand: "Lumen",
    category: "cameras",
    shape: "camera",
    price: 89,
    compareAt: 119,
    rating: 4.5,
    reviewCount: 3980,
    stock: 140,
    hues: ["#fbbf24", "#47310a"],
    colors: [COLORS.rose, COLORS.sky, COLORS.ivory],
    tagline: "Prints in seconds. Memories forever.",
    description:
      "Point, shoot and watch your photo develop in front of you. Built-in selfie mirror and auto-exposure make it great for parties and travel.",
    highlights: ["Auto exposure", "Selfie mirror", "Credit-card-sized prints", "Fun colors"],
    specs: { Film: "Mini instant", Flash: "Auto", Battery: "2x AA", Weight: "307 g", Warranty: "1 year" },
    addedAt: NOW - 200 * DAY,
  },
  {
    id: "p14",
    slug: "kinetic-runner-flux",
    name: "Runner Flux Running Shoe",
    brand: "Kinetic",
    category: "footwear",
    shape: "sneaker",
    price: 139,
    rating: 4.7,
    reviewCount: 2890,
    stock: 160,
    badge: "New",
    hues: ["#ff6b3d", "#4a1505"],
    colors: [COLORS.coral, COLORS.graphite, COLORS.lime],
    sizes: SHOE_SIZES,
    tagline: "Responsive foam that gives back every stride.",
    description:
      "A breathable knit upper wraps a double-density foam midsole with a carbon-infused plate for snappy toe-offs. Daily trainer, tempo runner and everything between.",
    highlights: ["Nitro-infused foam", "Carbon-infused plate", "Recycled knit upper", "Grippy rubber outsole"],
    specs: { Drop: "8 mm", Weight: "248 g (M9)", Use: "Road running", Upper: "Recycled knit", Warranty: "6 months" },
    addedAt: NOW - 9 * DAY,
  },
  {
    id: "p15",
    slug: "kinetic-court-classic",
    name: "Court Classic Leather Sneaker",
    brand: "Kinetic",
    category: "footwear",
    shape: "sneaker",
    price: 99,
    compareAt: 120,
    rating: 4.6,
    reviewCount: 4500,
    stock: 220,
    hues: ["#fb923c", "#4a2208"],
    colors: [COLORS.ivory, COLORS.graphite, COLORS.forest],
    sizes: SHOE_SIZES,
    tagline: "The icon, rebuilt for today.",
    description:
      "Full-grain leather, a cushioned insole and a vulcanized sole. The sneaker that goes with literally everything in your closet.",
    highlights: ["Full-grain leather", "Cushioned insole", "Vulcanized rubber sole", "Pairs with everything"],
    specs: { Upper: "Full-grain leather", Sole: "Vulcanized rubber", Closure: "Lace-up", Weight: "380 g", Warranty: "6 months" },
    addedAt: NOW - 300 * DAY,
  },
  {
    id: "p16",
    slug: "kinetic-trail-apex",
    name: "Trail Apex Hiking Shoe",
    brand: "Kinetic",
    category: "footwear",
    shape: "sneaker",
    price: 169,
    rating: 4.8,
    reviewCount: 1210,
    stock: 48,
    hues: ["#ea580c", "#431407"],
    colors: [COLORS.forest, COLORS.sand, COLORS.graphite],
    sizes: SHOE_SIZES,
    tagline: "Grip that refuses to quit.",
    description:
      "A waterproof membrane, aggressive 5mm lugs and a rock plate keep your feet protected whether you're scrambling scree or crossing creeks.",
    highlights: ["Waterproof membrane", "5mm multi-direction lugs", "Rock plate", "Gusseted tongue"],
    specs: { Waterproof: "Yes", Lugs: "5 mm", Weight: "392 g", Use: "Trail & hiking", Warranty: "1 year" },
    addedAt: NOW - 55 * DAY,
  },
  {
    id: "p17",
    slug: "northfold-heavyweight-hoodie",
    name: "Heavyweight Organic Hoodie",
    brand: "Northfold",
    category: "fashion",
    shape: "hoodie",
    price: 89,
    rating: 4.7,
    reviewCount: 3120,
    stock: 250,
    badge: "Best seller",
    hues: ["#94a3b8", "#1e293b"],
    colors: [COLORS.graphite, COLORS.sand, COLORS.forest, COLORS.rose],
    sizes: APPAREL_SIZES,
    tagline: "480gsm of weighty comfort.",
    description:
      "Cut from 100% organic cotton with a brushed interior, a double-lined hood and reinforced seams. Gets better with every wash.",
    highlights: ["480gsm organic cotton", "Double-lined hood", "Boxy relaxed fit", "Pre-washed, no shrink"],
    specs: { Fabric: "100% organic cotton", Fit: "Relaxed", Care: "Machine wash cold", Origin: "Portugal", Warranty: "30-day returns" },
    addedAt: NOW - 100 * DAY,
  },
  {
    id: "p18",
    slug: "northfold-storm-shell-jacket",
    name: "Storm Shell Waterproof Jacket",
    brand: "Northfold",
    category: "fashion",
    shape: "hoodie",
    price: 219,
    compareAt: 279,
    rating: 4.8,
    reviewCount: 884,
    stock: 36,
    hues: ["#64748b", "#0f172a"],
    colors: [COLORS.midnight, COLORS.amber, COLORS.sky],
    sizes: APPAREL_SIZES,
    tagline: "Rain? What rain?",
    description:
      "A 3-layer waterproof-breathable shell with fully taped seams, pit zips and a stowable hood. Packs into its own pocket.",
    highlights: ["3-layer 20k/20k fabric", "Fully taped seams", "Pit zips", "Packs into pocket"],
    specs: { Fabric: "3L recycled nylon", Waterproofing: "20,000 mm", Breathability: "20,000 g/m²", Weight: "410 g", Warranty: "Lifetime" },
    addedAt: NOW - 35 * DAY,
  },
  {
    id: "p19",
    slug: "strata-everyday-backpack",
    name: "Everyday 24L Backpack",
    brand: "Strata",
    category: "fashion",
    shape: "bag",
    price: 119,
    rating: 4.8,
    reviewCount: 2210,
    stock: 95,
    badge: "Editor's pick",
    hues: ["#a1a1aa", "#27272a"],
    colors: [COLORS.graphite, COLORS.sand, COLORS.forest],
    tagline: "The one bag for work, gym and weekends.",
    description:
      "Weatherproof ballistic nylon, a padded 16\" laptop sleeve, hidden passport pocket and a luggage pass-through for travel days.",
    highlights: ["Weatherproof ballistic nylon", "Fits 16\" laptop", "Luggage pass-through", "Hidden anti-theft pocket"],
    specs: { Capacity: "24L", Material: "1680D ballistic nylon", Weight: "980 g", Dimensions: "46 x 30 x 17 cm", Warranty: "Lifetime" },
    addedAt: NOW - 80 * DAY,
  },
  {
    id: "p20",
    slug: "strata-weekender-duffel",
    name: "Weekender 40L Duffel",
    brand: "Strata",
    category: "fashion",
    shape: "bag",
    price: 149,
    compareAt: 179,
    rating: 4.6,
    reviewCount: 640,
    stock: 31,
    hues: ["#a8a29e", "#292524"],
    colors: [COLORS.sand, COLORS.graphite],
    tagline: "Pack for three days in one carry-on.",
    description:
      "Waxed canvas with leather trims and a separate shoe compartment. It's carry-on friendly and designed to age beautifully.",
    highlights: ["Waxed canvas + leather", "Shoe compartment", "Carry-on size", "Detachable strap"],
    specs: { Capacity: "40L", Material: "Waxed canvas", Weight: "1.3 kg", Dimensions: "52 x 28 x 26 cm", Warranty: "Lifetime" },
    addedAt: NOW - 140 * DAY,
  },
  {
    id: "p21",
    slug: "halcyon-arc-floor-lamp",
    name: "Arc Floor Lamp",
    brand: "Halcyon",
    category: "home",
    shape: "lamp",
    price: 189,
    rating: 4.6,
    reviewCount: 530,
    stock: 44,
    badge: "New",
    hues: ["#fde047", "#3f2f04"],
    colors: [COLORS.amber, COLORS.graphite, COLORS.ivory],
    tagline: "Warm light that arcs over your sofa.",
    description:
      "A sculptural arc with a marble base, dimmable warm-white LED and touch control. Smart-home compatible.",
    highlights: ["Dimmable warm-white LED", "Marble base", "Touch + app control", "Smart-home compatible"],
    specs: { Height: "198 cm", Light: "2700K, 900 lm", Base: "Carrara marble", Power: "12W", Warranty: "2 years" },
    addedAt: NOW - 14 * DAY,
  },
  {
    id: "p22",
    slug: "halcyon-cloud-lounge-chair",
    name: "Cloud Lounge Chair",
    brand: "Halcyon",
    category: "home",
    shape: "chair",
    price: 449,
    compareAt: 599,
    rating: 4.9,
    reviewCount: 1180,
    stock: 18,
    badge: "Best seller",
    hues: ["#facc15", "#422006"],
    colors: [COLORS.sand, COLORS.forest, COLORS.coral],
    tagline: "Sink in. Stay a while.",
    description:
      "High-resilience foam in a bouclé cover, on solid oak legs. The chair your reading corner has been waiting for.",
    highlights: ["Bouclé performance fabric", "Solid oak legs", "High-resilience foam", "Removable cover"],
    specs: { Width: "78 cm", Frame: "Solid oak", Fabric: "Bouclé polyester", Weight: "14 kg", Warranty: "3 years" },
    addedAt: NOW - 70 * DAY,
  },
  {
    id: "p23",
    slug: "halcyon-desk-lamp-mini",
    name: "Mini Desk Lamp",
    brand: "Halcyon",
    category: "home",
    shape: "lamp",
    price: 59,
    rating: 4.5,
    reviewCount: 2750,
    stock: 200,
    hues: ["#fcd34d", "#3b2a05"],
    colors: [COLORS.ivory, COLORS.graphite, COLORS.sky],
    tagline: "Focused light for focused work.",
    description:
      "Flicker-free LED, wireless charging base and five brightness levels. Folds flat for travel.",
    highlights: ["Flicker-free LED", "10W wireless charging base", "5 brightness levels", "Folds flat"],
    specs: { Height: "42 cm", Light: "2700-6500K", Power: "9W", Charging: "10W Qi", Warranty: "1 year" },
    addedAt: NOW - 160 * DAY,
  },
  {
    id: "p24",
    slug: "halcyon-ergo-desk-chair",
    name: "Ergo Pro Desk Chair",
    brand: "Halcyon",
    category: "home",
    shape: "chair",
    price: 329,
    compareAt: 399,
    rating: 4.7,
    reviewCount: 1960,
    stock: 52,
    hues: ["#eab308", "#3a2b04"],
    colors: [COLORS.graphite, COLORS.ivory],
    tagline: "Eight hours in. Still comfortable.",
    description:
      "Breathable mesh back, 4D armrests, adjustable lumbar and a synchro-tilt mechanism. Built for people who actually work at their desk.",
    highlights: ["Breathable mesh", "4D armrests", "Adjustable lumbar", "12-year frame warranty"],
    specs: { "Weight capacity": "150 kg", Frame: "Aluminum", Tilt: "Synchro, 4-position lock", Weight: "17 kg", Warranty: "12 years" },
    addedAt: NOW - 110 * DAY,
  },
];

export const products: Product[] = catalog.map((p) => ({ ...p, images: photosFor(p.id) }));

export const brands = Array.from(new Set(products.map((p) => p.brand))).sort();

export function getProduct(idOrSlug: string): Product | undefined {
  return products.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
}

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function related(product: Product, count = 4): Product[] {
  const sameCat = products.filter((p) => p.category === product.category && p.id !== product.id);
  const others = products.filter((p) => p.category !== product.category && p.id !== product.id);
  return [...sameCat, ...others].slice(0, count);
}

export function discountPct(p: Product): number {
  return p.compareAt ? Math.round(((p.compareAt - p.price) / p.compareAt) * 100) : 0;
}
